title: Nicks First Blog
author: Nick O
email: nick@chinogordo.com
description: > # this means to ignore newlines until "baseurl:"
  Initial site for Nick at chinogordo.  Thoughts of first coding programs using github
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
